//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantRWPF.PlantRRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/PlantRServ")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalPlant", Namespace="http://schemas.datacontract.org/2004/07/PlantRServ.DataAccess")]
    [System.SerializableAttribute()]
    public partial class PersonalPlant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlantRWPF.PlantRRef.Account AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlantRWPF.PlantRRef.Plant PlantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int aidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime lastwateredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime nextwateredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int wdurationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlantRWPF.PlantRRef.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlantRWPF.PlantRRef.Plant Plant {
            get {
                return this.PlantField;
            }
            set {
                if ((object.ReferenceEquals(this.PlantField, value) != true)) {
                    this.PlantField = value;
                    this.RaisePropertyChanged("Plant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int aid {
            get {
                return this.aidField;
            }
            set {
                if ((this.aidField.Equals(value) != true)) {
                    this.aidField = value;
                    this.RaisePropertyChanged("aid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime lastwatered {
            get {
                return this.lastwateredField;
            }
            set {
                if ((this.lastwateredField.Equals(value) != true)) {
                    this.lastwateredField = value;
                    this.RaisePropertyChanged("lastwatered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime nextwatered {
            get {
                return this.nextwateredField;
            }
            set {
                if ((this.nextwateredField.Equals(value) != true)) {
                    this.nextwateredField = value;
                    this.RaisePropertyChanged("nextwatered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nname {
            get {
                return this.nnameField;
            }
            set {
                if ((object.ReferenceEquals(this.nnameField, value) != true)) {
                    this.nnameField = value;
                    this.RaisePropertyChanged("nname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pid {
            get {
                return this.pidField;
            }
            set {
                if ((this.pidField.Equals(value) != true)) {
                    this.pidField = value;
                    this.RaisePropertyChanged("pid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int wduration {
            get {
                return this.wdurationField;
            }
            set {
                if ((this.wdurationField.Equals(value) != true)) {
                    this.wdurationField = value;
                    this.RaisePropertyChanged("wduration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/PlantRServ.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlantRWPF.PlantRRef.PersonalPlant[] PersonalPlantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlantRWPF.PlantRRef.PersonalPlant[] PersonalPlants {
            get {
                return this.PersonalPlantsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalPlantsField, value) != true)) {
                    this.PersonalPlantsField = value;
                    this.RaisePropertyChanged("PersonalPlants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plant", Namespace="http://schemas.datacontract.org/2004/07/PlantRServ.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Plant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlantRWPF.PlantRRef.PersonalPlant[] PersonalPlantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imgurlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sdaysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlantRWPF.PlantRRef.PersonalPlant[] PersonalPlants {
            get {
                return this.PersonalPlantsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalPlantsField, value) != true)) {
                    this.PersonalPlantsField = value;
                    this.RaisePropertyChanged("PersonalPlants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cname {
            get {
                return this.cnameField;
            }
            set {
                if ((object.ReferenceEquals(this.cnameField, value) != true)) {
                    this.cnameField = value;
                    this.RaisePropertyChanged("cname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imgurl {
            get {
                return this.imgurlField;
            }
            set {
                if ((object.ReferenceEquals(this.imgurlField, value) != true)) {
                    this.imgurlField = value;
                    this.RaisePropertyChanged("imgurl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lname {
            get {
                return this.lnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lnameField, value) != true)) {
                    this.lnameField = value;
                    this.RaisePropertyChanged("lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sdays {
            get {
                return this.sdaysField;
            }
            set {
                if ((this.sdaysField.Equals(value) != true)) {
                    this.sdaysField = value;
                    this.RaisePropertyChanged("sdays");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlantRRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        PlantRWPF.PlantRRef.CompositeType GetDataUsingDataContract(PlantRWPF.PlantRRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.CompositeType> GetDataUsingDataContractAsync(PlantRWPF.PlantRRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPersonalPlant", ReplyAction="http://tempuri.org/IService1/AddPersonalPlantResponse")]
        int AddPersonalPlant(int plantID, int accID, int daysWater, string nName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPersonalPlant", ReplyAction="http://tempuri.org/IService1/AddPersonalPlantResponse")]
        System.Threading.Tasks.Task<int> AddPersonalPlantAsync(int plantID, int accID, int daysWater, string nName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindPersonalPlant", ReplyAction="http://tempuri.org/IService1/FindPersonalPlantResponse")]
        PlantRWPF.PlantRRef.PersonalPlant FindPersonalPlant(int ppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindPersonalPlant", ReplyAction="http://tempuri.org/IService1/FindPersonalPlantResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.PersonalPlant> FindPersonalPlantAsync(int ppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPersonalPlants", ReplyAction="http://tempuri.org/IService1/GetAllPersonalPlantsResponse")]
        PlantRWPF.PlantRRef.PersonalPlant[] GetAllPersonalPlants();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPersonalPlants", ReplyAction="http://tempuri.org/IService1/GetAllPersonalPlantsResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.PersonalPlant[]> GetAllPersonalPlantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccountPersonalPlants", ReplyAction="http://tempuri.org/IService1/GetAccountPersonalPlantsResponse")]
        PlantRWPF.PlantRRef.PersonalPlant[] GetAccountPersonalPlants(int accID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccountPersonalPlants", ReplyAction="http://tempuri.org/IService1/GetAccountPersonalPlantsResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.PersonalPlant[]> GetAccountPersonalPlantsAsync(int accID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemovePersonalPlant", ReplyAction="http://tempuri.org/IService1/RemovePersonalPlantResponse")]
        bool RemovePersonalPlant(int ppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemovePersonalPlant", ReplyAction="http://tempuri.org/IService1/RemovePersonalPlantResponse")]
        System.Threading.Tasks.Task<bool> RemovePersonalPlantAsync(int ppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePersonalPlant", ReplyAction="http://tempuri.org/IService1/UpdatePersonalPlantResponse")]
        PlantRWPF.PlantRRef.PersonalPlant UpdatePersonalPlant(PlantRWPF.PlantRRef.PersonalPlant pp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePersonalPlant", ReplyAction="http://tempuri.org/IService1/UpdatePersonalPlantResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.PersonalPlant> UpdatePersonalPlantAsync(PlantRWPF.PlantRRef.PersonalPlant pp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAccount", ReplyAction="http://tempuri.org/IService1/AddAccountResponse")]
        PlantRWPF.PlantRRef.Account AddAccount(string userName, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAccount", ReplyAction="http://tempuri.org/IService1/AddAccountResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Account> AddAccountAsync(string userName, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindAccount", ReplyAction="http://tempuri.org/IService1/FindAccountResponse")]
        PlantRWPF.PlantRRef.Account FindAccount(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindAccount", ReplyAction="http://tempuri.org/IService1/FindAccountResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Account> FindAccountAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllAccounts", ReplyAction="http://tempuri.org/IService1/GetAllAccountsResponse")]
        PlantRWPF.PlantRRef.Account[] GetAllAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllAccounts", ReplyAction="http://tempuri.org/IService1/GetAllAccountsResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Account[]> GetAllAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveAccount", ReplyAction="http://tempuri.org/IService1/RemoveAccountResponse")]
        bool RemoveAccount(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveAccount", ReplyAction="http://tempuri.org/IService1/RemoveAccountResponse")]
        System.Threading.Tasks.Task<bool> RemoveAccountAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLastAccount", ReplyAction="http://tempuri.org/IService1/GetLastAccountResponse")]
        PlantRWPF.PlantRRef.Account GetLastAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLastAccount", ReplyAction="http://tempuri.org/IService1/GetLastAccountResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Account> GetLastAccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPlant", ReplyAction="http://tempuri.org/IService1/AddPlantResponse")]
        int AddPlant(string cName, string lName, string imageURL, string description, int sDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPlant", ReplyAction="http://tempuri.org/IService1/AddPlantResponse")]
        System.Threading.Tasks.Task<int> AddPlantAsync(string cName, string lName, string imageURL, string description, int sDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindPlant", ReplyAction="http://tempuri.org/IService1/FindPlantResponse")]
        PlantRWPF.PlantRRef.Plant FindPlant(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindPlant", ReplyAction="http://tempuri.org/IService1/FindPlantResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Plant> FindPlantAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePlant", ReplyAction="http://tempuri.org/IService1/UpdatePlantResponse")]
        PlantRWPF.PlantRRef.Plant UpdatePlant(int id, string cName, string lName, string imageURL, string description, int sDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePlant", ReplyAction="http://tempuri.org/IService1/UpdatePlantResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Plant> UpdatePlantAsync(int id, string cName, string lName, string imageURL, string description, int sDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePlant", ReplyAction="http://tempuri.org/IService1/DeletePlantResponse")]
        bool DeletePlant(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePlant", ReplyAction="http://tempuri.org/IService1/DeletePlantResponse")]
        System.Threading.Tasks.Task<bool> DeletePlantAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPlants", ReplyAction="http://tempuri.org/IService1/GetAllPlantsResponse")]
        PlantRWPF.PlantRRef.Plant[] GetAllPlants();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPlants", ReplyAction="http://tempuri.org/IService1/GetAllPlantsResponse")]
        System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Plant[]> GetAllPlantsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PlantRWPF.PlantRRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PlantRWPF.PlantRRef.IService1>, PlantRWPF.PlantRRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public PlantRWPF.PlantRRef.CompositeType GetDataUsingDataContract(PlantRWPF.PlantRRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.CompositeType> GetDataUsingDataContractAsync(PlantRWPF.PlantRRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int AddPersonalPlant(int plantID, int accID, int daysWater, string nName) {
            return base.Channel.AddPersonalPlant(plantID, accID, daysWater, nName);
        }
        
        public System.Threading.Tasks.Task<int> AddPersonalPlantAsync(int plantID, int accID, int daysWater, string nName) {
            return base.Channel.AddPersonalPlantAsync(plantID, accID, daysWater, nName);
        }
        
        public PlantRWPF.PlantRRef.PersonalPlant FindPersonalPlant(int ppID) {
            return base.Channel.FindPersonalPlant(ppID);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.PersonalPlant> FindPersonalPlantAsync(int ppID) {
            return base.Channel.FindPersonalPlantAsync(ppID);
        }
        
        public PlantRWPF.PlantRRef.PersonalPlant[] GetAllPersonalPlants() {
            return base.Channel.GetAllPersonalPlants();
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.PersonalPlant[]> GetAllPersonalPlantsAsync() {
            return base.Channel.GetAllPersonalPlantsAsync();
        }
        
        public PlantRWPF.PlantRRef.PersonalPlant[] GetAccountPersonalPlants(int accID) {
            return base.Channel.GetAccountPersonalPlants(accID);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.PersonalPlant[]> GetAccountPersonalPlantsAsync(int accID) {
            return base.Channel.GetAccountPersonalPlantsAsync(accID);
        }
        
        public bool RemovePersonalPlant(int ppID) {
            return base.Channel.RemovePersonalPlant(ppID);
        }
        
        public System.Threading.Tasks.Task<bool> RemovePersonalPlantAsync(int ppID) {
            return base.Channel.RemovePersonalPlantAsync(ppID);
        }
        
        public PlantRWPF.PlantRRef.PersonalPlant UpdatePersonalPlant(PlantRWPF.PlantRRef.PersonalPlant pp) {
            return base.Channel.UpdatePersonalPlant(pp);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.PersonalPlant> UpdatePersonalPlantAsync(PlantRWPF.PlantRRef.PersonalPlant pp) {
            return base.Channel.UpdatePersonalPlantAsync(pp);
        }
        
        public PlantRWPF.PlantRRef.Account AddAccount(string userName, string email, string password) {
            return base.Channel.AddAccount(userName, email, password);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Account> AddAccountAsync(string userName, string email, string password) {
            return base.Channel.AddAccountAsync(userName, email, password);
        }
        
        public PlantRWPF.PlantRRef.Account FindAccount(string email) {
            return base.Channel.FindAccount(email);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Account> FindAccountAsync(string email) {
            return base.Channel.FindAccountAsync(email);
        }
        
        public PlantRWPF.PlantRRef.Account[] GetAllAccounts() {
            return base.Channel.GetAllAccounts();
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Account[]> GetAllAccountsAsync() {
            return base.Channel.GetAllAccountsAsync();
        }
        
        public bool RemoveAccount(string email) {
            return base.Channel.RemoveAccount(email);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAccountAsync(string email) {
            return base.Channel.RemoveAccountAsync(email);
        }
        
        public PlantRWPF.PlantRRef.Account GetLastAccount() {
            return base.Channel.GetLastAccount();
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Account> GetLastAccountAsync() {
            return base.Channel.GetLastAccountAsync();
        }
        
        public int AddPlant(string cName, string lName, string imageURL, string description, int sDays) {
            return base.Channel.AddPlant(cName, lName, imageURL, description, sDays);
        }
        
        public System.Threading.Tasks.Task<int> AddPlantAsync(string cName, string lName, string imageURL, string description, int sDays) {
            return base.Channel.AddPlantAsync(cName, lName, imageURL, description, sDays);
        }
        
        public PlantRWPF.PlantRRef.Plant FindPlant(int id) {
            return base.Channel.FindPlant(id);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Plant> FindPlantAsync(int id) {
            return base.Channel.FindPlantAsync(id);
        }
        
        public PlantRWPF.PlantRRef.Plant UpdatePlant(int id, string cName, string lName, string imageURL, string description, int sDays) {
            return base.Channel.UpdatePlant(id, cName, lName, imageURL, description, sDays);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Plant> UpdatePlantAsync(int id, string cName, string lName, string imageURL, string description, int sDays) {
            return base.Channel.UpdatePlantAsync(id, cName, lName, imageURL, description, sDays);
        }
        
        public bool DeletePlant(int id) {
            return base.Channel.DeletePlant(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePlantAsync(int id) {
            return base.Channel.DeletePlantAsync(id);
        }
        
        public PlantRWPF.PlantRRef.Plant[] GetAllPlants() {
            return base.Channel.GetAllPlants();
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.PlantRRef.Plant[]> GetAllPlantsAsync() {
            return base.Channel.GetAllPlantsAsync();
        }
    }
}
