//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantRWPF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/PlantRServ")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plant", Namespace="http://schemas.datacontract.org/2004/07/PlantRServ.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PlantRWPF.ServiceReference1.PersonalPlant))]
    public partial class Plant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SDaysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CName {
            get {
                return this.CNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CNameField, value) != true)) {
                    this.CNameField = value;
                    this.RaisePropertyChanged("CName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LName {
            get {
                return this.LNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LNameField, value) != true)) {
                    this.LNameField = value;
                    this.RaisePropertyChanged("LName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SDays {
            get {
                return this.SDaysField;
            }
            set {
                if ((this.SDaysField.Equals(value) != true)) {
                    this.SDaysField = value;
                    this.RaisePropertyChanged("SDays");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalPlant", Namespace="http://schemas.datacontract.org/2004/07/PlantRServ.Model")]
    [System.SerializableAttribute()]
    public partial class PersonalPlant : PlantRWPF.ServiceReference1.Plant {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastWateredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NextWateredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlantRWPF.ServiceReference1.Account accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlantRWPF.ServiceReference1.Plant plantField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AId {
            get {
                return this.AIdField;
            }
            set {
                if ((this.AIdField.Equals(value) != true)) {
                    this.AIdField = value;
                    this.RaisePropertyChanged("AId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Id")]
        public int Id1 {
            get {
                return this.Id1Field;
            }
            set {
                if ((this.Id1Field.Equals(value) != true)) {
                    this.Id1Field = value;
                    this.RaisePropertyChanged("Id1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastWatered {
            get {
                return this.LastWateredField;
            }
            set {
                if ((this.LastWateredField.Equals(value) != true)) {
                    this.LastWateredField = value;
                    this.RaisePropertyChanged("LastWatered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NName {
            get {
                return this.NNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NNameField, value) != true)) {
                    this.NNameField = value;
                    this.RaisePropertyChanged("NName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NextWatered {
            get {
                return this.NextWateredField;
            }
            set {
                if ((this.NextWateredField.Equals(value) != true)) {
                    this.NextWateredField = value;
                    this.RaisePropertyChanged("NextWatered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PId {
            get {
                return this.PIdField;
            }
            set {
                if ((this.PIdField.Equals(value) != true)) {
                    this.PIdField = value;
                    this.RaisePropertyChanged("PId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WDuration {
            get {
                return this.WDurationField;
            }
            set {
                if ((this.WDurationField.Equals(value) != true)) {
                    this.WDurationField = value;
                    this.RaisePropertyChanged("WDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlantRWPF.ServiceReference1.Account account {
            get {
                return this.accountField;
            }
            set {
                if ((object.ReferenceEquals(this.accountField, value) != true)) {
                    this.accountField = value;
                    this.RaisePropertyChanged("account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlantRWPF.ServiceReference1.Plant plant {
            get {
                return this.plantField;
            }
            set {
                if ((object.ReferenceEquals(this.plantField, value) != true)) {
                    this.plantField = value;
                    this.RaisePropertyChanged("plant");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/PlantRServ.Model")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlantRWPF.ServiceReference1.PersonalPlant[] PlantListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlantRWPF.ServiceReference1.PersonalPlant[] PlantList {
            get {
                return this.PlantListField;
            }
            set {
                if ((object.ReferenceEquals(this.PlantListField, value) != true)) {
                    this.PlantListField = value;
                    this.RaisePropertyChanged("PlantList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        PlantRWPF.ServiceReference1.CompositeType GetDataUsingDataContract(PlantRWPF.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(PlantRWPF.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPersonalPlant", ReplyAction="http://tempuri.org/IService1/AddPersonalPlantResponse")]
        int AddPersonalPlant(int plantID, int accID, int daysWater, string nName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPersonalPlant", ReplyAction="http://tempuri.org/IService1/AddPersonalPlantResponse")]
        System.Threading.Tasks.Task<int> AddPersonalPlantAsync(int plantID, int accID, int daysWater, string nName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindPersonalPlant", ReplyAction="http://tempuri.org/IService1/FindPersonalPlantResponse")]
        PlantRWPF.ServiceReference1.PersonalPlant FindPersonalPlant(int ppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindPersonalPlant", ReplyAction="http://tempuri.org/IService1/FindPersonalPlantResponse")]
        System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.PersonalPlant> FindPersonalPlantAsync(int ppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPersonalPlants", ReplyAction="http://tempuri.org/IService1/GetAllPersonalPlantsResponse")]
        PlantRWPF.ServiceReference1.PersonalPlant[] GetAllPersonalPlants();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPersonalPlants", ReplyAction="http://tempuri.org/IService1/GetAllPersonalPlantsResponse")]
        System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.PersonalPlant[]> GetAllPersonalPlantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccountPersonalPlants", ReplyAction="http://tempuri.org/IService1/GetAccountPersonalPlantsResponse")]
        PlantRWPF.ServiceReference1.PersonalPlant[] GetAccountPersonalPlants(int accID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccountPersonalPlants", ReplyAction="http://tempuri.org/IService1/GetAccountPersonalPlantsResponse")]
        System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.PersonalPlant[]> GetAccountPersonalPlantsAsync(int accID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemovePersonalPlant", ReplyAction="http://tempuri.org/IService1/RemovePersonalPlantResponse")]
        bool RemovePersonalPlant(int ppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemovePersonalPlant", ReplyAction="http://tempuri.org/IService1/RemovePersonalPlantResponse")]
        System.Threading.Tasks.Task<bool> RemovePersonalPlantAsync(int ppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePersonalPlant", ReplyAction="http://tempuri.org/IService1/UpdatePersonalPlantResponse")]
        bool UpdatePersonalPlant(int ppID, int wDuration, string nName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePersonalPlant", ReplyAction="http://tempuri.org/IService1/UpdatePersonalPlantResponse")]
        System.Threading.Tasks.Task<bool> UpdatePersonalPlantAsync(int ppID, int wDuration, string nName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAccount", ReplyAction="http://tempuri.org/IService1/AddAccountResponse")]
        PlantRWPF.ServiceReference1.Account AddAccount(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAccount", ReplyAction="http://tempuri.org/IService1/AddAccountResponse")]
        System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Account> AddAccountAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindAccount", ReplyAction="http://tempuri.org/IService1/FindAccountResponse")]
        PlantRWPF.ServiceReference1.Account FindAccount(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindAccount", ReplyAction="http://tempuri.org/IService1/FindAccountResponse")]
        System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Account> FindAccountAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllAccounts", ReplyAction="http://tempuri.org/IService1/GetAllAccountsResponse")]
        PlantRWPF.ServiceReference1.Account[] GetAllAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllAccounts", ReplyAction="http://tempuri.org/IService1/GetAllAccountsResponse")]
        System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Account[]> GetAllAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveAccount", ReplyAction="http://tempuri.org/IService1/RemoveAccountResponse")]
        bool RemoveAccount(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveAccount", ReplyAction="http://tempuri.org/IService1/RemoveAccountResponse")]
        System.Threading.Tasks.Task<bool> RemoveAccountAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLastAccount", ReplyAction="http://tempuri.org/IService1/GetLastAccountResponse")]
        PlantRWPF.ServiceReference1.Account GetLastAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLastAccount", ReplyAction="http://tempuri.org/IService1/GetLastAccountResponse")]
        System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Account> GetLastAccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPlant", ReplyAction="http://tempuri.org/IService1/AddPlantResponse")]
        int AddPlant(string cName, string lName, string imageURL, string description, int sDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPlant", ReplyAction="http://tempuri.org/IService1/AddPlantResponse")]
        System.Threading.Tasks.Task<int> AddPlantAsync(string cName, string lName, string imageURL, string description, int sDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindPlant", ReplyAction="http://tempuri.org/IService1/FindPlantResponse")]
        PlantRWPF.ServiceReference1.Plant FindPlant(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindPlant", ReplyAction="http://tempuri.org/IService1/FindPlantResponse")]
        System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Plant> FindPlantAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePlant", ReplyAction="http://tempuri.org/IService1/UpdatePlantResponse")]
        PlantRWPF.ServiceReference1.Plant UpdatePlant(int id, string cName, string lName, string imageURL, string description, int sDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePlant", ReplyAction="http://tempuri.org/IService1/UpdatePlantResponse")]
        System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Plant> UpdatePlantAsync(int id, string cName, string lName, string imageURL, string description, int sDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePlant", ReplyAction="http://tempuri.org/IService1/DeletePlantResponse")]
        bool DeletePlant(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePlant", ReplyAction="http://tempuri.org/IService1/DeletePlantResponse")]
        System.Threading.Tasks.Task<bool> DeletePlantAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPlants", ReplyAction="http://tempuri.org/IService1/GetAllPlantsResponse")]
        PlantRWPF.ServiceReference1.Plant[] GetAllPlants();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPlants", ReplyAction="http://tempuri.org/IService1/GetAllPlantsResponse")]
        System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Plant[]> GetAllPlantsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PlantRWPF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PlantRWPF.ServiceReference1.IService1>, PlantRWPF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public PlantRWPF.ServiceReference1.CompositeType GetDataUsingDataContract(PlantRWPF.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(PlantRWPF.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int AddPersonalPlant(int plantID, int accID, int daysWater, string nName) {
            return base.Channel.AddPersonalPlant(plantID, accID, daysWater, nName);
        }
        
        public System.Threading.Tasks.Task<int> AddPersonalPlantAsync(int plantID, int accID, int daysWater, string nName) {
            return base.Channel.AddPersonalPlantAsync(plantID, accID, daysWater, nName);
        }
        
        public PlantRWPF.ServiceReference1.PersonalPlant FindPersonalPlant(int ppID) {
            return base.Channel.FindPersonalPlant(ppID);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.PersonalPlant> FindPersonalPlantAsync(int ppID) {
            return base.Channel.FindPersonalPlantAsync(ppID);
        }
        
        public PlantRWPF.ServiceReference1.PersonalPlant[] GetAllPersonalPlants() {
            return base.Channel.GetAllPersonalPlants();
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.PersonalPlant[]> GetAllPersonalPlantsAsync() {
            return base.Channel.GetAllPersonalPlantsAsync();
        }
        
        public PlantRWPF.ServiceReference1.PersonalPlant[] GetAccountPersonalPlants(int accID) {
            return base.Channel.GetAccountPersonalPlants(accID);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.PersonalPlant[]> GetAccountPersonalPlantsAsync(int accID) {
            return base.Channel.GetAccountPersonalPlantsAsync(accID);
        }
        
        public bool RemovePersonalPlant(int ppID) {
            return base.Channel.RemovePersonalPlant(ppID);
        }
        
        public System.Threading.Tasks.Task<bool> RemovePersonalPlantAsync(int ppID) {
            return base.Channel.RemovePersonalPlantAsync(ppID);
        }
        
        public bool UpdatePersonalPlant(int ppID, int wDuration, string nName) {
            return base.Channel.UpdatePersonalPlant(ppID, wDuration, nName);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePersonalPlantAsync(int ppID, int wDuration, string nName) {
            return base.Channel.UpdatePersonalPlantAsync(ppID, wDuration, nName);
        }
        
        public PlantRWPF.ServiceReference1.Account AddAccount(string email) {
            return base.Channel.AddAccount(email);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Account> AddAccountAsync(string email) {
            return base.Channel.AddAccountAsync(email);
        }
        
        public PlantRWPF.ServiceReference1.Account FindAccount(string email) {
            return base.Channel.FindAccount(email);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Account> FindAccountAsync(string email) {
            return base.Channel.FindAccountAsync(email);
        }
        
        public PlantRWPF.ServiceReference1.Account[] GetAllAccounts() {
            return base.Channel.GetAllAccounts();
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Account[]> GetAllAccountsAsync() {
            return base.Channel.GetAllAccountsAsync();
        }
        
        public bool RemoveAccount(string email) {
            return base.Channel.RemoveAccount(email);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAccountAsync(string email) {
            return base.Channel.RemoveAccountAsync(email);
        }
        
        public PlantRWPF.ServiceReference1.Account GetLastAccount() {
            return base.Channel.GetLastAccount();
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Account> GetLastAccountAsync() {
            return base.Channel.GetLastAccountAsync();
        }
        
        public int AddPlant(string cName, string lName, string imageURL, string description, int sDays) {
            return base.Channel.AddPlant(cName, lName, imageURL, description, sDays);
        }
        
        public System.Threading.Tasks.Task<int> AddPlantAsync(string cName, string lName, string imageURL, string description, int sDays) {
            return base.Channel.AddPlantAsync(cName, lName, imageURL, description, sDays);
        }
        
        public PlantRWPF.ServiceReference1.Plant FindPlant(int id) {
            return base.Channel.FindPlant(id);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Plant> FindPlantAsync(int id) {
            return base.Channel.FindPlantAsync(id);
        }
        
        public PlantRWPF.ServiceReference1.Plant UpdatePlant(int id, string cName, string lName, string imageURL, string description, int sDays) {
            return base.Channel.UpdatePlant(id, cName, lName, imageURL, description, sDays);
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Plant> UpdatePlantAsync(int id, string cName, string lName, string imageURL, string description, int sDays) {
            return base.Channel.UpdatePlantAsync(id, cName, lName, imageURL, description, sDays);
        }
        
        public bool DeletePlant(int id) {
            return base.Channel.DeletePlant(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePlantAsync(int id) {
            return base.Channel.DeletePlantAsync(id);
        }
        
        public PlantRWPF.ServiceReference1.Plant[] GetAllPlants() {
            return base.Channel.GetAllPlants();
        }
        
        public System.Threading.Tasks.Task<PlantRWPF.ServiceReference1.Plant[]> GetAllPlantsAsync() {
            return base.Channel.GetAllPlantsAsync();
        }
    }
}
